/**********************************************************************/
/* GENERATED FILE
/* Input: .\src\bss\bssCore.h
/* Date-Time: 19/1/2025 - 15:35
/**********************************************************************/

#include ""

// metagen_embedfile(somevar, C:\Users\moizi\OneDrive\Documents\Programming\C\base\src\bss\bssCore.h), line: 8
U8Array somevar = 
{	.data=(u8*)
	"#ifndef BSS_CORE_H\r\n"
	"#define BSS_CORE_H\r\n"
	"\r\n"
	"#include \"base\\baseCore.h\"\r\n"
	"#include \"base\\baseMemory.h\"\r\n"
	"#include \"base\\baseStrings.h\"\r\n"
	"\r\n"
	"metagen_embedfile(somevar, \"C:\\\\Users\\\\moizi\\\\OneDrive\\\\Documents\\\\Programming\\\\C\\\\base\\\\src\\\\bss\\\\bssCore.h\", text)\r\n"
	"typedef enum BssTokKind\r\n"
	"{\r\n"
	"    TOK_KIND_START = 257,\r\n"
	"    TOK_INT_LIT = TOK_KIND_START,\r\n"
	"    TOK_BOOL_LIT,\r\n"
	"    TOK_STR_LIT,\r\n"
	"    TOK_CHAR_LIT,\r\n"
	"    \r\n"
	"    TOK_IDEN,\r\n"
	"    TOK_IF,\r\n"
	"    TOK_ELSE,\r\n"
	"    TOK_PROJECT,\r\n"
	"    TOK_BUILD,\r\n"
	"    TOK_RUN,\r\n"
	"    TOK_FOR,\r\n"
	"    TOK_WHILE,\r\n"
	"    TOK_IN,\r\n"
	"\r\n"
	"    TOK_LOGICAL_OR_OP,\r\n"
	"    TOK_LOGICAL_AND_OP,\r\n"
	"    TOK_EQ_OP,\r\n"
	"    TOK_NEQ_OP,\r\n"
	"\r\n"
	"    TOK_END_INPUT,\r\n"
	"}BssTokKind;\r\n"
	"\r\n"
	"typedef struct BssTokPos\r\n"
	"{\r\n"
	"    struct BssLexerState *ownerLexer;\r\n"
	"    u64 line;\r\n"
	"    u64 col;\r\n"
	"\r\n"
	"    U8Array tokRange;\r\n"
	"}BssTokPos;\r\n"
	"\r\n"
	"typedef struct BssTok\r\n"
	"{\r\n"
	"    BssTokKind kind;\r\n"
	"    BssTokPos pos;\r\n"
	"\r\n"
	"    str8 lexeme;\r\n"
	"    bool isFmtStr;\r\n"
	"}BssTok;\r\n"
	"\r\n"
	"BASE_CREATE_ARRAY_VIEW_DECLS_DEFS(BssTokArray, BssTok);\r\n"
	"\r\n"
	"typedef struct BssTokChunkListNode\r\n"
	"{\r\n"
	"    struct BssTokChunkListNode *next;\r\n"
	"    struct BssTokChunkListNode *prev;\r\n"
	"\r\n"
	"    BssTokArray chunk;\r\n"
	"    u64 cap;\r\n"
	"}BssTokChunkListNode;\r\n"
	"\r\n"
	"typedef struct BssTokChunkList\r\n"
	"{\r\n"
	"    struct BssTokChunkListNode *first;\r\n"
	"    struct BssTokChunkListNode *last;\r\n"
	"\r\n"
	"    u64 len;\r\n"
	"    u64 totalLen;\r\n"
	"}BssTokChunkList;\r\n"
	"\r\n"
	"typedef struct BssLexerState\r\n"
	"{\r\n"
	"    struct BssLexerState *next;\r\n"
	"    struct BssLexerState *prev;\r\n"
	"\r\n"
	"    str8 filePath;\r\n"
	"    U8Array buffer;\r\n"
	"    BssTokArray lexedBssToks;\r\n"
	"\r\n"
	"    BssTok tok;\r\n"
	"    u64 nextBssTokIndex;\r\n"
	"\r\n"
	"    u8 ch;\r\n"
	"    u64 line;\r\n"
	"    u64 col;\r\n"
	"    u8 *currLocInBuffer;\r\n"
	"}BssLexerState;\r\n"
	"\r\n"
	"typedef struct BssParserState\r\n"
	"{\r\n"
	"    struct ASTProject *proj;\r\n"
	"}BssParserState;\r\n"
	"\r\n"
	"typedef struct BssCheckerState\r\n"
	"{\r\n"
	"    struct BssScope *rootScope;\r\n"
	"    \r\n"
	"    struct BssType *runOutput;\r\n"
	"    struct BssType *projectType;\r\n"
	"}BssCheckerState;\r\n"
	"\r\n"
	"typedef struct BSSInterpretorState\r\n"
	"{\r\n"
	"    BaseArena *lexerArena;\r\n"
	"    BaseArena *parserArena;\r\n"
	"    BaseArena *checkerArena;\r\n"
	"    \r\n"
	"    BssLexerState lState;\r\n"
	"    BssParserState pState;\r\n"
	"    BssCheckerState cState;\r\n"
	"\r\n"
	"    Str8List buildFlags;\r\n"
	"}BSSInterpretorState;\r\n"
	"\r\n"
	"void bssInterpFile(BSSInterpretorState *iState, str8 path);\r\n"
	"void bssInterpBuffer(BSSInterpretorState *iState, U8Array buffer);\r\n"
	"\r\n"
	"i64 bssGetEscapeCharValue(str8 escapeCharString);\r\n"
	"str8 bssGetStr8RepFromTokLexeme(BaseArena *arena, BssTok tok);\r\n"
	"\r\n"
	"bool bssHasFlag(BSSInterpretorState *iState, str8 flag);\r\n"
	"void bssAddFlag(BSSInterpretorState *iState, str8 flag);\r\n"
	"#endif",
	.len=2517,
};
