#include "jsonCore.h"

BASE_CREATE_EFFICIENT_LL_DEFS(JSONObjMembList, JSONObjMemb);
BASE_CREATE_LL_JUST_NODE_DEFS_EX(JSONValueList, JSONValueListNode, JSONValue)
BASE_CREATE_LL_JUST_LIST_DEFS_EX(JSONValueList, JSONValueListNode, JSONValue)