#include "baseCore.c"
#include "baseMemory.c"
#include "baseThreads.c"
#include "baseStrings.c"
#include "baseHash.c"
#include "baseCmdLine.c"
#include "baseMath.c"
#include "baseLog.c"
#include "baseUri.c"
#include "baseCLexer.c"
#include "baseMetagen.c"
#include "basePath.c"

#include "baseCoreTypes.gen.c"